"""Detecting code that was generated rather than written.

The source text is not the program. Across every ecosystem some of what runs was
produced by a tool: annotation processors, protobuf, Prisma, GraphQL codegen,
`go generate`, derive macros, source generators, ORM metaprogramming. Analysing
generated output as if a person wrote it produces confident nonsense in both
directions — it was not authored, and editing it by hand is futile because the
next build overwrites it.

Detection is language-general and needs no parser, because generated files
announce themselves. Two signals:

* **A header marker.** Conventions are widely shared — Go specifies
  ``// Code generated ... DO NOT EDIT.``, .NET emits ``<auto-generated/>``, and
  the bare ``@generated`` tag is common across ecosystems.
* **A path.** Build output and codegen conventionally live in known directories
  or carry known suffixes.

Markers are checked only in the first few lines, because generators put them
there and humans write prose everywhere.

**Detection is biased toward "authored" on purpose.** Calling authored code
generated means silently skipping verification of a real test file — the exact
hole this project exists to close. Calling generated code authored merely costs
a redundant check. So a bare "DO NOT EDIT" is not enough: plenty of human
comments say that. The marker must actually claim the file was generated.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from . import glob

#: How many leading lines may carry a marker. Generators put them first; a
#: mention further down is prose, not a declaration.
HEADER_LINES = 15

#: Each pattern must *claim generation*. "DO NOT EDIT" alone is deliberately
#: absent — "// do not edit without asking Priya" is a human comment on human
#: code, and treating it as generated would silently disable verification.
_MARKERS = (
    re.compile(r"@generated\b"),
    re.compile(r"Code generated\b.*\bDO NOT EDIT", re.I),
    re.compile(r"<auto-?generated", re.I),
    re.compile(r"\bauto-?generated\b", re.I),
    re.compile(r"\bautomatically generated\b", re.I),
    # Anchored to the start of a comment line: a real generator header opens with
    # this, whereas "the id is generated by the database" is prose about code.
    re.compile(r"^(?://|#|/\*+|\*|--|<!--|;|')*\s*(?:@)?generated by\s+[\w.@/-]+", re.I),
    re.compile(r"\bthis file (?:is|was) (?:auto[- ]?)?generated\b", re.I),
    re.compile(r"\bdo not (?:edit|modify)\b.*\bgenerat", re.I),
    re.compile(r"\bgenerat\w*\b.*\bdo not (?:edit|modify)\b", re.I),
)

#: Conventional locations and suffixes, across ecosystems. Extendable by policy.
DEFAULT_PATTERNS = (
    # JVM build output (Lombok, MapStruct, Dagger, Immutables, AutoValue, Querydsl)
    "**/target/generated-sources/**", "**/target/generated-test-sources/**",
    "**/build/generated/**", "**/build/generated-src/**",
    # Protocol buffers and gRPC, in every language
    "**/*_pb2.py", "**/*_pb2_grpc.py", "**/*_pb2.pyi", "**/*.pb.go", "**/*_grpc.pb.go",
    "**/*_pb.js", "**/*_pb.d.ts", "**/*.pb.cc", "**/*.pb.h",
    # Go conventions
    "**/*_generated.go", "**/zz_generated*.go", "**/mock_*.go",
    # JS/TS codegen: GraphQL, Prisma, OpenAPI, tRPC
    "**/__generated__/**", "**/*.generated.ts", "**/*.gen.ts", "**/graphql/generated/**",
    "**/prisma/client/**", "**/node_modules/.prisma/**",
    # .NET
    "**/*.designer.cs", "**/*.g.cs", "**/*.generated.cs",
    # Dart / Flutter
    "**/*.g.dart", "**/*.freezed.dart",
    # Generic conventions
    "**/generated/**", "**/gen/**", "**/*.pyc",
)


@dataclass(frozen=True)
class Generated:
    """Why a file is believed to be generated."""

    reason: str
    evidence: str

    def __str__(self) -> str:
        return self.reason


def detect(
    path: str, content: str | None = None, *, extra_patterns: tuple[str, ...] = ()
) -> Generated | None:
    """Return why ``path`` looks generated, or ``None`` if it looks authored."""
    pattern = glob.first_match(tuple(DEFAULT_PATTERNS) + tuple(extra_patterns), path)
    if pattern:
        return Generated(
            reason=f"path matches the generated-code pattern {pattern}",
            evidence=pattern,
        )

    marker = _marker(content)
    if marker:
        return Generated(
            reason=f"header declares it generated: {marker!r}",
            evidence=marker,
        )
    return None


def _marker(content: str | None) -> str | None:
    if not content:
        return None
    for line in content.splitlines()[:HEADER_LINES]:
        stripped = line.strip()
        if not stripped:
            continue
        for marker in _MARKERS:
            if marker.search(stripped):
                return stripped[:120]
    return None
