"""Generated code, across ecosystems.

Detection is biased toward "authored": misclassifying authored code as generated
silently skips verification of real tests, which is the hole this project exists
to close. Misclassifying generated code as authored only wastes a check.
"""

import unittest

from aegisflow.core.generated import detect
from aegisflow.core.policy import Policy
from aegisflow.core.verdict import Status
from aegisflow.verify import GENERATED_FILE_EDITED, verify_change


class TestMarkers(unittest.TestCase):
    """Generated files announce themselves, and the conventions are shared."""

    def test_go_convention(self):
        self.assertIsNotNone(
            detect("main.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\n"))

    def test_dotnet_convention(self):
        self.assertIsNotNone(detect("Model.cs", "//---\n// <auto-generated/>\n//---\n"))

    def test_bare_generated_tag(self):
        self.assertIsNotNone(detect("schema.ts", "/* eslint-disable */\n// @generated\n"))

    def test_generator_banner(self):
        self.assertIsNotNone(detect("c.ts", "// Generated by GraphQL Code Generator\n"))
        self.assertIsNotNone(detect("h.rb", "# Generated by protoc\n"))

    def test_prose_banner(self):
        self.assertIsNotNone(
            detect("m.py", "# This file was automatically generated by SQLAlchemy\n"))

    def test_marker_must_be_near_the_top(self):
        body = "\n".join(f"line {i}" for i in range(40)) + "\n# @generated\n"
        self.assertIsNone(detect("src/app.py", body))


class TestFalsePositivesAreRefused(unittest.TestCase):
    """The dangerous direction: authored code must never look generated."""

    def test_human_comment_saying_do_not_edit(self):
        self.assertIsNone(detect("src/app.ts", "// TODO: do not edit without asking Priya\n"))

    def test_prose_about_generated_values(self):
        self.assertIsNone(detect("src/db.py", "# The invoice id is generated by the database\n"))

    def test_docstring_mentioning_generation(self):
        self.assertIsNone(detect("src/ids.py", "'''Ids are generated by uuid4.'''\n"))

    def test_ordinary_test_file(self):
        self.assertIsNone(detect("tests/test_real.py", "def test_x():\n    assert a == 1\n"))

    def test_empty_content(self):
        self.assertIsNone(detect("src/app.py", ""))
        self.assertIsNone(detect("src/app.py", None))


class TestPaths(unittest.TestCase):
    def test_covers_many_ecosystems(self):
        for path in (
            "api/service_pb2.py",            # protobuf, Python
            "internal/store.pb.go",          # protobuf, Go
            "target/generated-sources/annotations/InvoiceMapperImpl.java",  # Lombok/MapStruct
            "build/generated/source/Dagger.java",   # Dagger
            "src/__generated__/types.ts",    # GraphQL codegen
            "lib/models/user.g.dart",        # Dart
            "Forms/Main.designer.cs",        # .NET
            "pkg/zz_generated.deepcopy.go",  # Kubernetes codegen
        ):
            self.assertIsNotNone(detect(path), path)

    def test_ordinary_source_paths_are_untouched(self):
        for path in ("src/generator.py", "tests/test_generated_ids.py", "src/gene/seq.py"):
            self.assertIsNone(detect(path, "x = 1\n"), path)

    def test_extra_patterns_extend_the_defaults(self):
        self.assertIsNone(detect("vendor/thrift/x.py", "x = 1\n"))
        self.assertIsNotNone(
            detect("vendor/thrift/x.py", "x = 1\n", extra_patterns=("**/vendor/thrift/**",)))


class TestVerifyBehaviour(unittest.TestCase):
    BEFORE = "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage main\nvar X = 1\n"
    AFTER = "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage main\nvar X = 2\n"
    PATH = "internal/api.pb.go"

    def test_hand_editing_generated_code_is_reported(self):
        verdict = verify_change(self.BEFORE, self.AFTER, self.PATH, Policy(), hand_edit=True)
        self.assertEqual([f.rule for f in verdict.findings], [GENERATED_FILE_EDITED])
        self.assertIn("regenerate", verdict.findings[0].prescription)

    def test_regeneration_in_a_diff_is_not_reported(self):
        """Committing regenerated output is normal; only hand-editing is not.

        No finding — but no pass either. Nothing in this change was analysed, so
        the honest status is UNVERIFIED. Returning PASS here would be the green
        banner RULES.md section 5 forbids.
        """
        verdict = verify_change(self.BEFORE, self.AFTER, self.PATH, Policy())
        self.assertIs(verdict.status, Status.UNVERIFIED)
        self.assertEqual(verdict.findings, ())

    def test_generated_file_is_never_counted_as_checked(self):
        verdict = verify_change(self.BEFORE, self.AFTER, self.PATH, Policy())
        self.assertEqual(verdict.checked, ())
        self.assertTrue(verdict.skipped)

    def test_generated_test_file_is_not_verified_as_authored(self):
        before = "# @generated\ndef test_x():\n    assert a == 1\n"
        after = "# @generated\ndef test_x():\n    assert a is not None\n"
        verdict = verify_change(before, after, "tests/test_gen.py", Policy())
        self.assertIs(verdict.status, Status.UNVERIFIED)
        self.assertIn("generated code", verdict.skipped[0])

    def test_authored_test_file_is_still_verified(self):
        verdict = verify_change(
            "def test_x():\n    assert a == 1\n",
            "def test_x():\n    assert a is not None\n",
            "tests/test_real.py", Policy(),
        )
        self.assertEqual([f.rule for f in verdict.findings], ["assertion_monotonicity"])

    def test_detection_can_be_disabled(self):
        """With detection off the file is not short-circuited as generated.

        It is still neither `checked` nor `skipped`: no rule applies to Go, and a
        file nothing examined must not look like one that passed.
        """
        policy = Policy.from_dict({"generated": {"detect": False}})
        verdict = verify_change(self.BEFORE, self.AFTER, self.PATH, policy, hand_edit=True)
        self.assertEqual(verdict.findings, ())
        self.assertEqual(
            verdict.skipped,
            (f"{self.PATH}: no rule in this policy applies to this file",),
            "it must be skipped for want of an analyser, not as generated code",
        )

    def test_severity_is_configurable(self):
        policy = Policy.from_dict({"generated": {"on_hand_edit": "escalate"}})
        verdict = verify_change(self.BEFORE, self.AFTER, self.PATH, policy, hand_edit=True)
        self.assertIs(verdict.status, Status.ESCALATE)

    def test_rule_can_be_turned_off_while_detection_stays_on(self):
        policy = Policy.from_dict({"generated": {"on_hand_edit": "off"}})
        verdict = verify_change(self.BEFORE, self.AFTER, self.PATH, policy, hand_edit=True)
        self.assertEqual(verdict.findings, ())
        self.assertTrue(verdict.skipped)


if __name__ == "__main__":
    unittest.main()
